### ISSUE TITLE
Tüv

### ISSUE THREAD

**Issue by KfzMatze45** [Sebihunter/VitaVillageMTA#2]
Der Tüv geht nicht, Also man kann ich zwar als Autofix Abfragen was er kostet.
Aber der Befehl Tuev geht nicht, Auch nicht als Ares Autohaus Mitarbeiter / Chef

**Comment by Sebihunter** [comment]
Wurde behoben in einem der letzten Commits.

**Comment by KfzMatze45** [comment]
Sebi, Das einzige was behoben wurde, Was ich zumindest gesehen habe ist das man den Tüv abfragen kann und dann erfährt man was er kostet. Aber den Tüv kann keiner geben. Bei den Bühnen von Ares Autohaus, Kein Ares Angestellter und kein Autofix Angestellter

**Comment by KfzMatze45** [comment]
Also Tüv geht,
